#! /bin/sh
#
# This script launch MiRA via the command line arguments parser in file
# "mira-batch.i".
#
this=$(readlink -mn "$0")
dir=$(dirname "$this")
if test "x$dir" = "x"; then
  dir=.
fi

exec yorick -batch "${dir}/mira-batch.i" "$@"
